galaxy_info:
  author: "Michael Vilain"
  description: install baseline packages and services
  # company: your company (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  # platforms:
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  #- name: GenericUNIX
  #  versions:
  #  - all
  #  - any
  #- name: OpenBSD
  #  versions:
  #  - all
  #  - 5.6
  #  - 5.7
  #  - 5.8
  #  - 5.9
  #  - 6.0
  - name: Fedora
    versions:
      - 21
      - 22 (untested, but should work)
      - 23 (untested, but should work)
      - 24
      - 25 (untested, but should work)
      - 26 (untested, but should work)
      - 27
  #- name: opensuse
  #  versions:
  #  - all
  #  - 12.1
  #  - 12.2
  #  - 12.3
  #  - 13.1
  #  - 13.2
  #- name: MacOSX
  #  versions:
  #  - all
  #  - 10.10
  #  - 10.11
  #  - 10.12
  #  - 10.7
  #  - 10.8
  #  - 10.9
  #- name: IOS
  #  versions:
  #  - all
  #  - any
  #- name: Solaris
  #  versions:
  #  - all
  #  - 10
  #  - 11.0
  #  - 11.1
  #  - 11.2
  #  - 11.3
  #- name: SmartOS
  #  versions:
  #  - all
  #  - any
  #- name: eos
  #  versions:
  #  - all
  #  - Any
  #- name: Windows
  #  versions:
  #  - all
  #  - 2012R2
  #- name: Amazon
  #  versions:
  #  - all
  #  - 2013.03
  #  - 2013.09
  #- name: GenericBSD
  #  versions:
  #  - all
  #  - any
  #- name: Junos
  #  versions:
  #  - all
  #  - any
  #- name: FreeBSD
  #  versions:
  #  - all
  #  - 10.0
  #  - 10.1
  #  - 10.2
  #  - 10.3
  #  - 8.0
  #  - 8.1
  #  - 8.2
  #  - 8.3
  #  - 8.4
  #  - 9.0
  #  - 9.1
  #  - 9.1
  #  - 9.2
  #  - 9.3
  - name: Ubuntu
    versions:
    #  - all
    #  - lucid
    #  - maverick
    #  - natty
    #  - oneiric
    - precise (12.04)
    # - quantal
    # - raring
    # - saucy
    - trusty (14.04)
    # - utopic
    # - vivid
    # - wily
    - xenial (16.04)
    - zesty (17.04)
    - artful (17.10)
    # - bionic
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  #  - 11SP4
  #  - 12
  #  - 12SP1
  #- name: GenericLinux
  #  versions:
  #  - all
  #  - any
  #- name: NXOS
  #  versions:
  #  - all
  #  - any
  - name: Debian
    versions:
    - 8.0 (jessie)
    - 9.0 (stretch)

  galaxy_tags:
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.
    - networking

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.