---
# place any variables specific to the virtualbox install 
# and configuration here for multiple platforms

vb_version: "6.1.6"     # released April 14 2020
deb_vb_keyurl: https://www.virtualbox.org/download
deb_vb_key: oracle_vbox_2016.asc
deb_vb_old_key: oracle_vbox.asc

rhel_vb_keyurl: https://www.virtualbox.org/download
rhel_vb_key: oracle_vbox.asc
