# install virtualbox on RedHat systems
---

### this won't work if you're behind a proxy server
- name: adding repo key
  shell: "rpm --import https://www.virtualbox.org/download/oracle_vbox.asc"
  args:
    warn: false
  register: vb_rpm_key
# - debug: var=vb_rpm_key

- name: adding Fedora repo
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    file: virtualbox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    enabled: yes

- name: installing 5.0 version (this may take few minutes)
  yum:
    name: "VirtualBox-5.0"
    state: latest
    update_cache: yes
  register: vb50_install
  when: ansible_distribution_major_version|int == 21
# - debug: var=vb50_install

- name: installing 5.1 version (this may take few minutes)
  dnf:
    name: "VirtualBox-5.1"
    state: latest
  register: vb51_install
  when: 
  - ansible_distribution_major_version|int < 26
  - ansible_distribution_major_version|int > 21
# - debug: var=vb51_install

# starting with F29, VB lumps all versions in same directory, so exclude 5.2
# https://www.virtualbox.org/ticket/18113
# 5/18/20 says F29 dnf virtualbox 6.1 has errors (libm + libvpx missing?)
# dnf module won't install it, but dnf command works
# note: exclude added in ansible 2.7 but can't send array...fixed in 2.7.15
- name: installing lastest version (this may take a while)
  command: dnf install -y VirtualBox-6.1 --exclude VirtualBox-5.2,VirtualBox-6.0
  args:
    warn: no
  register: vb6_install
  when: ansible_distribution_major_version|int >= 26
#- debug: var=vb6_install.stdout_lines
