# install virtualbox on RedHat systems
---

### this won't work if you're behind a proxy server
- name: adding repo key
  shell: "rpm --import https://www.virtualbox.org/download/oracle_vbox.asc"
  args:
    warn: false
  register: vb_rpm_key
# - debug: var=vb_rpm_key

- name: adding Fedora repo
  yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    file: virtualbox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    enabled: yes

- name: installing older version (this may take few minutes)
  package:
    name: VirtualBox-5.0
    state: present
    # update_cache: yes
  register: vb_install
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int < 24
# - debug: var=vb_install

- name: installing current version (this may take few minutes)
  package:
    name: VirtualBox-6.1
    state: present
  register: vb_install
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 24
# - debug: var=vb_install
