# install virtualbox on Rocky systems
---

### this won't work if you're behind a proxy server
- name: adding repo key
  shell: "rpm --import https://www.virtualbox.org/download/oracle_vbox.asc"
  args:
    warn: false
  register: vb_rpm_key
# - debug: var=vb_rpm_key

- name: adding RHEL repo
  yum_repository:
    name: virtualbox
    description: Oracle Linux / RHEL / CentOS-$releasever / $basearch - VirtualBox
    file: virtualbox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    enabled: yes

# 7/23/22 virtualbox doesn't install on RockyLinux 9
- name: installing current version (this may take few minutes)
  package:
    name: VirtualBox-6.1
    state: present
  register: vb_install
  when: ansible_distribution_major_version|int <= 8
# - debug: var=vb_install
